# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/DatosBook',
                'doc_host': 'https://dci-courses.github.io',
                'git_url': 'https://github.com/dci-courses/DatosBook',
                'lib_path': 'DatosBook'},
  'syms': {'DatosBook.core': {'DatosBook.core.foo': ('core.html#foo', 'DatosBook/core.py')}}}
