---
title: "p5 con ml5"
format:
  html:
    css: p5testing.css

toc: true
toc-location: right
toc-depth: 3
---

## Hello

<div id="p5-sketch">
  <div id="canvas-container"></div>
  <div id="button-container"></div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.9.0/p5.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.9.0/addons/p5.dom.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.9.0/addons/p5.sound.min.js"></script>
<script src="https://unpkg.com/ml5@0.12.2/dist/ml5.min.js"></script>

<script>
(function() {
  const sketch = (p) => {
    let mobilenet;
    let classifier;
    let video;
    let label = '.....';
    let happyButton;
    let sadButton;
    let trainButton;

    p.modelReady = function() {
      console.log('Model is ready!!!');
    }

    p.videoReady = function() {
      console.log('Video is ready!!!');
    }

    p.whileTraining = function(loss) {
      if (loss == null) {
        console.log('Training Complete');
        classifier.classify(p.gotResults);
      } else {
        console.log(loss);
      }
    }

    p.gotResults = function(error, result) {
      if (error) {
        console.error(error);
      } else {
        console.log(result);
        label = result[0].label;
        classifier.classify(p.gotResults);
      }
    }

    p.setup = function() {
      p.createCanvas(320, 270).parent('canvas-container');
      video = p.createCapture(p.VIDEO);
      video.hide();
      p.background(0);
      mobilenet = ml5.featureExtractor('MobileNet', p.modelReady);
      classifier = mobilenet.classification(video, p.videoReady);

      happyButton = p.createButton('happy');
      happyButton.mousePressed(function() {
        classifier.addImage('happy');
      }).parent('button-container');

      sadButton = p.createButton('sad');
      sadButton.mousePressed(function() {
        classifier.addImage('sad');
      }).parent('button-container');

      trainButton = p.createButton('train');
      trainButton.mousePressed(function() {
        classifier.train(p.whileTraining);
      }).parent('button-container');
    }

    p.draw = function() {
      p.background(0);
      p.image(video, 0, 0, 320, 240);
      p.fill(255);
      p.textSize(16);
      p.text(label, 10, p.height - 10);
    }
  };

  new p5(sketch);
})();
</script>

## Bye